### PR TITLE
Transport redesign, general cleanup

### PR DESCRIPTION
**Pull request by ekweible**
@computmaxer

### CODE REVIEW

**Comment by computmaxer** [comment]
**_classic_** Evan PR

**Comment by computmaxer** [comment]
The only thing I would say about all of this is that I am not a huge fan of having two model classes for the same data, e.g. `Chug` and `TChug`. Perhaps you're planning to change that with the move to fine-grained pubsub?

**Comment by ekweible** [comment]
I definitely get that.. but this is how I see it:

The `TGame` class represents the data exactly as it will be transported with no additional API and no restrictions when constructing (like not allowing the `id` field to be set via ctor or something). Ideally, this class could/should be generated.

The `Game` class is designed with the application usage in mind - there's a .create() constructor which only allows setting fields that make sense (omitting fields that the server will populate) and there can be additional APIs (like `friendlyChugTime`) as well as a `.change()` method that allows you to incrementally modify entities without affecting the original copy.

For some of the models, they could be one in the same, but there's not always a 1-to-1 mapping from server to client (game entity has `seconds_until_chug`, but the client uses that to expose a synced chug time as well as an always-up-to-date getter for `timeUntilChug`.

**Comment by computmaxer** [comment]
I guess I just don't see much value in the extra layer - to me the transport classes can just be can just be represented as Map/json. The regular models already have a `prepForTransport`, that (or a similar method) may as well just return a Map. It doesn't seem like properties would be accessed much (other than maybe `game_id` and `id`) after handing it off to the transport layer.

I guess the extra layer doesn't bother me _that_ much, I'm just concerned about it adding another place/opportunity/layer for a bug when changing something about the data model.

Assuming we keep it, why are the static `encodeEntity` and `decodeEntity` functions located in the Transport and not on the respective `TEntity` classes? Seems like that would be something that makes them a little more useful as a class (hadn't seen those until now).

**Pull request merged**
